import feedparser
import smtplib
import os
import html
import json
import tempfile
import shutil
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo


# -----------------------------
# Configuration
# -----------------------------

INTERNAL_TARGETS = [
	email.strip()
	for email in os.environ.get("digest_internal_targets", "").split(",")
	if email.strip()
]

EXTERNAL_TARGETS = [
	email.strip()
	for email in os.environ.get("digest_external_targets", "").split(",")
	if email.strip()
]

if not INTERNAL_TARGETS:
	INTERNAL_TARGETS = ["internal@email.com"]

if not EXTERNAL_TARGETS:
	EXTERNAL_TARGETS = ["external@email.com"]

CISA_FEED = "https://www.cisa.gov/cybersecurity-advisories/all.xml"

FEEDS = [
	CISA_FEED,
	"https://krebsonsecurity.com/feed/",
	"https://feeds.feedburner.com/TheHackersNews",
	"https://www.darkreading.com/rss.xml",
	"https://techcrunch.com/feed/",
	"https://www.schneier.com/blog/atom.xml",
	"https://www.bleepingcomputer.com/feed/",
	"https://www.wired.com/feed/category/security/latest/rss",
	"https://www.wired.com/feed/tag/ai/latest/rss"
]

STATE_FILE = "sent_articles.json"

CUTOFF_TIME = datetime.now(timezone.utc) - timedelta(hours=24)
LOCAL_TZ = ZoneInfo("America/New_York")


# -----------------------------
# State Handling
# -----------------------------

def load_sent_articles():
	if not os.path.exists(STATE_FILE) or os.path.getsize(STATE_FILE) == 0:
		return set()

	try:
		with open(STATE_FILE, "r", encoding="utf-8") as f:
			data = json.load(f)
		return set(data)
	except Exception:
		return set()


def save_sent_articles(sent_set):
	try:
		with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False) as tmp:
			json.dump(list(sent_set), tmp)
			tmp_path = tmp.name
		shutil.move(tmp_path, STATE_FILE)
	except Exception as e:
		print(f"Failed to save state: {e}")


# -----------------------------
# Helpers
# -----------------------------

def extract_datetime(entry):
	if entry.get("published_parsed"):
		return datetime(*entry.published_parsed[:6], tzinfo=timezone.utc)
	if entry.get("updated_parsed"):
		return datetime(*entry.updated_parsed[:6], tzinfo=timezone.utc)
	return None


def send_email(subject, recipients, html_content):
	if not recipients:
		return

	msg = MIMEMultipart("alternative")
	msg["Subject"] = subject
	msg["From"] = os.environ.get("digest_email")
	msg["To"] = ", ".join(recipients)

	msg.attach(MIMEText(html_content, "html"))

	with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
		server.login(
			os.environ.get("digest_email"),
			os.environ.get("digest_app_password")
		)
		server.sendmail(msg["From"], recipients, msg.as_string())


# -----------------------------
# Main Logic
# -----------------------------

def main():
	sent_articles = load_sent_articles()
	new_articles = []
	cisa_alerts = []

	for url in FEEDS:
		feed = feedparser.parse(url)

		for entry in feed.entries:
			published = extract_datetime(entry)

			if not published or published < CUTOFF_TIME:
				continue

			if entry.link in sent_articles:
				continue

			article_data = {
				"title": html.escape(entry.title),
				"link": entry.link,
				"source": feed.feed.title,
				"published": published
			}

			if url == CISA_FEED:
				cisa_alerts.append(article_data)
			else:
				new_articles.append(article_data)

	new_articles.sort(key=lambda x: x["published"], reverse=True)
	cisa_alerts.sort(key=lambda x: x["published"], reverse=True)

	current_time_str = datetime.now(LOCAL_TZ).strftime("%b %d, %Y at %I:%M %p %Z")

# -----------------------------
# Build CISA Section
# -----------------------------

	if cisa_alerts:
		cisa_items = "\n".join(
			f'''
<li>
	<small>{a['published'].astimezone(LOCAL_TZ).strftime('%b %d, %Y at %I:%M %p %Z')}</small><br>
	<a href="{a['link']}">{a['title']}</a>
</li>
'''.strip()
			for a in cisa_alerts
		)

		cisa_section = f'''
<h3>CISA Alerts</h3>
<ul>
{cisa_items}
</ul>
'''
	else:
		cisa_section = '''
<h3>CISA Alerts</h3>
<p>No CISA alerts at this time.</p>
'''

# -----------------------------
# Build Shared Body
# -----------------------------

	if new_articles:
		list_items = "\n".join(
			f'''
<li>
	<b>{a['source']}</b><br>
	<small>{a['published'].astimezone(LOCAL_TZ).strftime('%b %d, %Y at %I:%M %p %Z')}</small><br>
	<a href="{a['link']}">{a['title']}</a>
</li>
'''.strip()
			for a in new_articles
		)

		body_section = f'''
<h3>Articles</h3>
<p>{len(new_articles)} new article(s) since last email.</p>
<ul>
{list_items}
</ul>
'''
	else:
		body_section = "<p>No new articles since last email.</p>"

# -----------------------------
# Internal Email
# -----------------------------

	internal_html = f'''
<html>
	<body>
		<h2>Cyber-Digest</h2>
		{cisa_section}
		{body_section}
			<div class="footer">
            Generated by Braxton's Cyber-Digest •
			Last updated: {current_time_str}
			</div>
	</body>
</html>
'''

# -----------------------------
# External Email
# -----------------------------

	external_html = f'''
<html>
	<body>
		<h2>Cyber-Digest</h2>
		{cisa_section}
		{body_section}
			<div class="footer">
			Last updated: {current_time_str}
			</div>
	</body>
</html>
'''

# -----------------------------
# Send Emails
# -----------------------------

	send_email("Internal Cyber Digest", INTERNAL_TARGETS, internal_html)
	send_email("Cyber Digest", EXTERNAL_TARGETS, external_html)

# -----------------------------
# Update State
# -----------------------------

	for article in new_articles + cisa_alerts:
		sent_articles.add(article["link"])

	save_sent_articles(sent_articles)


if __name__ == "__main__":
	main()
